### ISSUE TITLE
Index error in p_struct_def_1

### ISSUE THREAD

**Issue by jay-o-stotch** [zayfod/pyfranca#1]
franca_parser.py line 604: 
`p[0] = ast.Struct(name=p[2], fields=p[4], flags=p[3])`
`fields=p[4]` should be `fields=p[5]`

struct_def : STRUCT ID flag_defs '{' struct_fields '}'
p[1]: STRUCT
p[2]: ID
p[3]: glag_defs
p[4]: '{'
**p[5]: struct_fields**
p[6]: '}'

**Comment by zayfod** [comment]
Thanks for catching this!

**Comment by jay-o-stotch** [comment]
Thanks for fixing
