### ISSUE TITLE
Bug in Fidl Import

### ISSUE THREAD

**Issue by jb090979** [zayfod/pyfranca#10]
The current Version 0.3.0 of pyfranca cannot import a chain of fidl file. 
If A.fidl import B.fild, wich imports C.fidl causes the error that all Symbols in C.fidl are missing, because C.fidl isn't processed. 

I check the pyfranca code and may found the root cause. I create a pull request with an unittest that show the problem. See pull request 11 for further details.
https://github.com/zayfod/pyfranca/pull/11

**Comment by zayfod** [comment]
Fixed in 5cec01090923914b3729ffe72153a87a6c401ac5 . Thanks!
