### ISSUE TITLE
looking for a class to validate franca packages

### ISSUE THREAD

**Issue by jb090979** [zayfod/pyfranca#3]
Currently pyfranca "only" generates the ast from the fidl file. I am looking for a way to validate the fidl files. Checking for undefined types, broken imports etc. I add franca_validator.py. You can add several fidl packages to class Validator and then validate the parsed packages. The corresponding unittests show you how to use it. franca_validator.py is far away from being finished. But it should give you an impression, what I mean.

Enclosed please find a zip file with some modifications on pyfranca.
[pyfranca.zip](https://github.com/zayfod/pyfranca/files/777876/pyfranca.zip)

**Comment by zayfod** [comment]
Thanks for opening a separate issue for this.

I assume that the archive is the same as the one in issue #2.

I will push first working version of my code merged with yours later today or tomorrow. I am working on updating your unit tests to work with the new code.

**Comment by zayfod** [comment]
OK, I just pushed first working implementation. There are features that are still not fully supported (e.g. FQN references, extends, and proper interface member visibility). These will come soon as part of the final v0.2 .

I think all of the use cases that you suggested are covered. Your feedback will be appreciated. Also more unit tests are welcome!

I want to add two command-line tools that take advantage of the new Processor class - fidl_verify.py and fidl_dump.py (to visualize, paresed AST).

**Comment by jb090979** [comment]
looks  good at first view.  Good Job.
After my vacation next week I get on with checking your commits.

**Comment by zayfod** [comment]
OK. Looking forward to your input. Closing the issue for now.
